services:
  store_manager_dev.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: store_manager_dev.db
    environment:
      - ACCEPT_EULA: "Y"
      - SA_PASSWORD: "yourStrong(!)Password"
    ports:
      - "1433:1433"
    volumes:
      - ./.containers/db:/var/lib/mssql/data

  storemanager.api:
    ports:
      - "5088:80"
      - "7157:443"
    image: ${DOCKER_REGISTRY-}storemanagerapi
    build:
      context: .
      dockerfile: ./StoreManager.API/Dockerfile
    environment:
      - "ASPNETCORE_ENVIRONMENT": "Development"
      - "ASPNETCORE_URLS": "https://+:7157;http://+:5088"
      #- "ASPNETCORE_HTTP_PORT": "5088"
      #- "ASPNETCORE_Kestrel__Certificates__Default__Password": "eeJD2puyfUyYYPXfQt"
      #- "ASPNETCORE_Kestrel__Certificates__Default__Path": "/https/aspnetapp.pfx"
      - "ConnectionStrings:DefaultConnection": "Data Source=localhost,1433;Database=storemanager_dev.db;Application Name=StoreManager;Integrated Security=false;User ID=SA;Password=yourStrong(!)Password;TrustServerCertificate=True;"
    #volumes:
      #- ~/.aspnet/https:/https:ro
    depends_on:
      - storemanager_dev.db