services:
  storemanager_dev.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: storemanager_dev.db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1433:1433"
    volumes:
      - ./.containers/db:/var/lib/mssql/data
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "yourStrong(!)Password" -Q "SELECT 1" -C || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - storemanager-network

  storemanager.api:
    image: ${DOCKER_REGISTRY-}storemanagerapi
    build:
      context: .
      dockerfile: src/StoreManager.API/Dockerfile
    ports:
      - "5088:8080"
      #- "7157:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URL=http://localhost
      - ASPNETCORE_HTTP_PORT=5088
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=eeJD2puyfUyYYPXfQt
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ConnectionStrings:DefaultConnection=Data Source=storemanager_dev.db,1433;Database=storemanager_dev.db;Application Name=StoreManager;Integrated Security=false;User ID=SA;Password=yourStrong(!)Password;TrustServerCertificate=True;
    #volumes:
      #- ~/.aspnet/https:/https:ro
    depends_on:
      storemanager_dev.db:
        condition: service_healthy
    networks:
      - storemanager-network
  
  storemanager.webapp:
    image: ${DOCKER_REGISTRY-}storemanagerwebapp
    container_name: storemanager.webapp
    build:
      context: .
      dockerfile: src/StoreManager.Webapp/StoreManager.Webapp/Dockerfile
    ports:
      - "5001:8080"
      #- "7077:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=http://+:8082
      - ASPNETCORE_URL=http://localhost
      - ASPNETCORE_HTTP_PORT=5001
      - ApiSettings:BaseUrl=http://localhost:5001
    #volumes:
      #- ~/.aspnet/https:/https:ro
    depends_on:
      - storemanager.api
    networks:
      - storemanager-network

networks:
  storemanager-network:
    driver: bridge